apiVersion: v1
kind: PersistentVolume
metadata:
  name: system-storage
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  nfs:
    path: /exports/user-vols/system-storage
    server: nfsopenshift.ase.local
  persistentVolumeReclaimPolicy: Retain
